In [1]:
import pandas as pd
import numpy as np
import os

In [12]:
# load all the data from this path
files = os.listdir()
dfs = [pd.read_csv(f) for f in files if f.endswith(".csv")]
dfs = dfs[2:]

In [13]:
# concat all dfs
df = pd.concat(dfs)
df.sort_values(by="metric", ascending=False)

     num_features model  accuracy  metric method
0               4   SVM     0.660    7250    sfm
1               3   SVM     0.627    7000    sfm
0               2   SVM     0.598    6950    seq
2               5   SVM     0.659    6850    sfm
1               3    NN     0.599    6800    seq
..            ...   ...       ...     ...    ...
146            25    RF     0.514     150   mean
148            25   LDA     0.515    -200   mean
147            25    LR     0.514    -200   mean
149            25    NN     0.519    -250   corr
149            25   SVM     0.491    -250   mean

[900 rows x 5 columns]

In [14]:
df.sort_values(by="accuracy", ascending=False)

    num_features model  accuracy  metric method
38            12   SVM     0.724    5700    sfm
32            11   SVM     0.719    5850    sfm
43            13   SVM     0.718    5500    sfm
25            10   SVM     0.713    5950    sfm
13             8   SVM     0.711    6400    sfm
..           ...   ...       ...     ...    ...
13             4    RF     0.482    4500   mean
43             5   SVM     0.475    3650   mean
10             2   XGB     0.474    5000    rfe
42             6   SVM     0.472    3650   mean
41             4   SVM     0.471    3650   mean

[900 rows x 5 columns]